version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/agent-support/intellij"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(intellij)"
